language: node_js
node_js:
  - "12"
branches:
  only:
    - master

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  repo: oct16/oct16.github.io
  target_branch: mini-vue-example
  skip_cleanup: true
  keep_history: true
  allow_empty_commit: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  on:
    branch: master
